base_url = "https://docs.angelscript-ue.g1sgame.com"
title = "AngelScript虚幻引擎文档"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
logo = "angelscript_unreal.png"