site_name: Unreal Engine Angelscript
nav:
  - Home: 'index.md'
  - 'installation.md'
  - 'getting-started.md'
  - 'angelscript-features.md'
  - 'cpp-usage.md'
  - 'using-precompiled-data.md'
  - 'development-status.md'
  - 'license.md'
  - 'Discord Server': 'https://discord.gg/39wmC2e'
theme: readthedocs
extra_css: [extra.css]
